#! /usr/bin/env ruby
# Write S3 Log Format to Apache Combined Log Format
#   via http://sixones.com/2012/11/06/s3-logs-into-combined-log-format.html
#
#   http://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html
#   http://httpd.apache.org/docs/1.3/logs.html#combined
#

$stdin.each_line do |line|
  if line =~ /[\w+] ([\w\.]+) \[([^\]]+)\] ([\d\.]+) (?:[\w-])* (?:[\w-])* (?:[\w\.]+) ([^\s]+)? (?:[^\s"]*)(?:"([^"]+)"|-) ([\d-]+) ([\w-]+) ([\d-]+) ([\d-]+) ([\d-]+) ([\d-]+) (?:"([^"]+)"|-) (?:"([^"]+)"|-) (?:\w+|-)/i
    
    # 1 => host
    # 2 => date + time
    # 3 => client address
    # 4 => path
    # 5 => request
    # 6 => status code
    # 7 => error code
    # 8 => bytes sent
    # 9 => total bytes
    # 10 => total time
    # 11 => turn around time
    # 12 => referrer
    # 13 => user agent
    
    $stdout.write %Q(#{$3} - [#{$2}] "#{$5}" #{$6} #{$8} "#{$12}" "#{$13}"\n")
  end
end
